In [5]:
import numpy as np

In [35]:
np.random.seed(80)
rand_array = np.random.randint(1, 100, (4, 4))
print(rand_array)
#a
display('rand_array > 50', rand_array > 50)
#b
display('nsum axis=0 columns:', rand_array.sum(axis=0))
display('nsum axis=1 rows:', rand_array.sum(axis=1))
#c - np.min np.max np.mean השתמש בפונקציות
#i 
display('sum axis=0 columns:max', rand_array.max(axis=0))
display('sum axis=1 rows:max', rand_array.max(axis=1))
#ii
display('sum axis=0 columns:min', rand_array.min(axis=0))
display('sum axis=1 rows:min', rand_array.min(axis=1))
#iii
display('sum axis=0 columns:mean', rand_array.mean(axis=0))
display('sum axis=1 rows:mean', rand_array.mean(axis=1))

[[48 61 39 84]
 [11 51  4 87]
 [24 16 82  6]
 [65 10 93 43]]


'rand_array > 50'

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False, False,  True, False],
       [ True, False,  True, False]])

'nsum axis=0 columns:'

array([148, 138, 218, 220])

'nsum axis=1 rows:'

array([232, 153, 128, 211])

'sum axis=0 columns:max'

array([65, 61, 93, 87], dtype=int32)

'sum axis=1 rows:max'

array([84, 87, 82, 93], dtype=int32)

'sum axis=0 columns:min'

array([11, 10,  4,  6], dtype=int32)

'sum axis=1 rows:min'

array([39,  4,  6, 10], dtype=int32)

'sum axis=0 columns:mean'

array([37. , 34.5, 54.5, 55. ])

'sum axis=1 rows:mean'

array([58.  , 38.25, 32.  , 52.75])